---
title: "network_graph_rpub"
author: "James Hutt"
fig_width: 24
fig_heigh: 8

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(igraph)
library(tidyverse)

```

```{r state_relations, include=FALSE}

# Suppressed the warning message as it is just information about the column
# parsing types

x <- read_csv("raw-data/statenetworks.csv", 
              na = c("", "NA"))

x <- x %>%
  select(State1, State2, Border, RaceDif, State1_Pop, State2_Pop) %>% 
  mutate(logpop = log(State1_Pop / 500000, 3)) %>% 
  mutate(s1_larger = ifelse(State1_Pop >= State2_Pop, TRUE, FALSE)) %>%
  mutate(inverse_racedif = 1 / RaceDif)

```

```{r network_graph_unique, echo=FALSE}

# Repeat the same process but filtering only for edges where state 1 is larger.
# This should mean each pair of vertices is only joine by 1 edge. Since the
# weights were symmetric this should have no effect.

edge_list_unique <- x %>%
  filter(Border == 1) %>%
  filter(s1_larger == TRUE)

state_data <- x %>%
  filter(State1 %in% c(edge_list_unique$State1, edge_list_unique$State2)) %>%
  select(State1, State1_Pop, logpop) %>%
  distinct()

network_inv_race_unique <- graph_from_data_frame(edge_list_unique, directed = FALSE, vertices = state_data) %>%
  set_edge_attr("weight", value = edge_list_unique$inverse_racedif)

l <- layout_with_fr(network_inv_race_unique)
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

plot.igraph(network_inv_race_unique, 
     layout= l, 
     rescale = FALSE,
     vertex.color = "gray",
     vertex.frame.color = "blue", 
     vertex.label.dist = 0,
     vertex.label.cex = 0.4,
     main="US States Separated By Racial Differences Across Bordering States:\n Sized by Population",
     frame = F,
     vertex.size = 5 * V(network_inv_race_unique)$logpop)

# Reproduce plot but with degree causing sizing 

deg <- degree(network_inv_race_unique, mode = "all")

plot.igraph(network_inv_race_unique, 
     layout= l, 
     rescale = FALSE,
     vertex.color = "gray",
     vertex.frame.color = "blue", 
     vertex.label.dist = 0,
     vertex.label.cex = 0.4,
     main="US States Separated By Racial Differences Across Bordering States: \n Sized by Number of State Borders",
     frame = F,
     vertex.size = 3 * deg)
  


```